# -*- coding: utf-8 -*-
"""Indice de masa corporal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gR1HPURcRTufEmZbwOC7QYgiDtg8vD06
"""

print("*****Sistema de medicion de indice de masa corporal*****")

peso = float(input("Porfavor ingrese su peso: "))

altura = float(input("Porfavor ingrese su altura: "))

altura = altura**2

IMC = peso / altura

IMC = round(IMC, 2)

if(IMC < 18.5): print("Porfavor coma alguito, ud esta re flac@ " + str(IMC))

elif(IMC >= 18.5 and IMC <= 24.9): print("Estamos melos, su peso es normal :) "+ str(IMC))

elif(IMC > 25 and IMC <= 26.9):print("Cierre esa geta que va pa arriba mk ud tiene sobre peso grado 1:) "+ str(IMC))

elif(IMC > 27 and IMC <= 29.9): print("le dije que cierre la geta, ud tiene sobre peso grado 2:) "+ str(IMC))

elif(IMC > 30 and IMC <= 34.9): print("Ud no quiere caminar sino rodar, :V deje la tragadera que ya esta obeso grado 1 "+ str(IMC))

elif(IMC > 35 and IMC <= 39.9): print("Ud tiene obesidad grado 2 Deje de tragar MK "+ str(IMC))

elif(IMC > 40 and IMC <= 49.9): print("Ud necesita ayuda, su obesidad es grado 3 (Morbida) "+ str(IMC))

elif(IMC > 50): print("Ud tiene ganas de conocer a San Pedro muy rápido, tiene obesidad extrema "+ str(IMC))